### ISSUE TITLE
empty datalayer on /checkout/finish?

### ISSUE THREAD

**Issue by shopworksnl** [webmatch/WbmTagManagerEcomm#27] opened 2020-12-09 13:02 UTC
Hi,

We experience an empty datalayer on the /checkout/finish?xxxxxxx page.

![image](https://user-images.githubusercontent.com/14836152/101633119-1e372c80-3a27-11eb-9ef8-a5cb0f6e564e.png)

What could be wrong here?

**Comment by wbm-sbasler** [comment] 2020-12-10 07:12
Can you please stick to the ["reporting a bug"-template](https://github.com/webmatch/WbmTagManagerEcomm/issues/16)? 
Otherwise it is not possible to check your problem and get back to you with a qualified answer?

**Comment by shopworksnl** [comment] 2020-12-10 09:34
**Description:**
We experience an empty datalayer on the /checkout/finish?xxxxxxx page.

**Plugin & Shopware version:** 
SW 6.3.3.1, plugin 1.1.2

**Steps to reproduce:**
Place an order on www.swisse.nl, article test. After succesful payment (through an external payment srvice provider) the user is redirected from the PSP to the shopware finish page (see url screenshot). We view the source of the finish page and see and empty datalayer (see image provided)

**Expected result:**
In the datalayer we expect the fields as setup in the backend under settings of WBM tag manager (/admin#/wbm/property/list/frontend.checkout.finish.page)

**Current result:** 
datalayer (null)

**Comment by wbm-sbasler** [comment] 2021-01-19 08:01
I can't reproduce it in our demoshop: http://sw6.webmatch.de/
Please update to the latest version and let us know if the issue still exists.

**Comment by wbm-sbasler** [comment] 2021-05-17 11:37
@shopworksnl I assume that this issue is resolved so i close it.

**Closed by wbm-sbasler** 2021-05-17 11:37 UTC
